env:
  node: true
  es2021: true
  browser: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project: ./tsconfig.api.json
  tsconfigRootDir: ./

plugins:
  - '@typescript-eslint'

rules:
  # Основные правила
  no-console: off
  no-debugger: off
  no-unused-vars: off
  
  # TypeScript правила
  @typescript-eslint/no-unused-vars: off
  @typescript-eslint/no-explicit-any: warn
  @typescript-eslint/explicit-function-return-type: off
  @typescript-eslint/no-parameter-properties: off
  @typescript-eslint/no-use-before-define: off
  @typescript-eslint/consistent-type-imports: error
  @typescript-eslint/no-unsafe-assignment: off
  @typescript-eslint/no-unsafe-member-access: off
  @typescript-eslint/no-unsafe-call: off
  @typescript-eslint/no-unsafe-return: off
  @typescript-eslint/restrict-template-expressions: off

  # Правила для API-тестов
  max-lines-per-function: off
  complexity: off
  max-statements: off

overrides:
  - files:
      - API-Tests/**/*.ts
    rules:
      no-undef: off
      no-unused-vars: off
      @typescript-eslint/no-require-imports: off
      @typescript-eslint/no-non-null-assertion: off