/**
 * Все возможные состояния исполнительного производства
 */
export const ENFORCEMENT_STATES = {
    ENFORCEMENT_DOCUMENT_RECEIVED: "ENFORCEMENT_DOCUMENT_RECEIVED",
    TYPO_CORRECTION_RECEIVED: "TYPO_CORRECTION_RECEIVED",
    TYPO_CORRECTION_REQUESTED: "TYPO_CORRECTION_REQUESTED",
    TYPO_CORRECTION_LEFT_WITHOUT_ACTION: "TYPO_CORRECTION_LEFT_WITHOUT_ACTION",

    BANK_BLOCK_ACCOUNTS: "BANK_BLOCK_ACCOUNTS",
    BANK_WAITING_DOCUMENT: "BANK_WAITING_DOCUMENT",
    BANK_DOCUMENT_RECALL: "BANK_DOCUMENT_RECALL",
    BANK_DOCUMENT_RETURNED: "BANK_DOCUMENT_RETURNED",

    PFR_WITHHOLDING: "PFR_WITHHOLDING",
    PFR_WAITING_DOCUMENT: "PFR_WAITING_DOCUMENT",
    PFR_DOCUMENT_RECALL: "PFR_DOCUMENT_RECALL",
    PFR_DOCUMENT_RETURNED: "PFR_DOCUMENT_RETURNED",

    FSSP_SENDING_DOCUMENT: "FSSP_SENDING_DOCUMENT",
    FSSP_STARTED: "FSSP_STARTED",
    FSSP_STATUS_REQUEST: "FSSP_STATUS_REQUEST",
    FSSP_WAITING_DOCUMENT: "FSSP_WAITING_DOCUMENT",
    FSSP_DOCUMENT_RECALL: "FSSP_DOCUMENT_RECALL",
    FSSP_DOCUMENT_RETURNED: "FSSP_DOCUMENT_RETURNED",

    PROCEEDING_FINISHED_WITHOUT_DOCUMENT: "PROCEEDING_FINISHED_WITHOUT_DOCUMENT",
    PROCEEDING_FINISHED_WITH_DOCUMENT: "PROCEEDING_FINISHED_WITH_DOCUMENT",

    SENDING_TO_PARTNERS: "SENDING_TO_PARTNERS",

    REFUSAL: "REFUSAL",

    COURT_ORDER_CANCELLATION: "COURT_ORDER_CANCELLATION",
    COURT_DECISION_CANCELLATION: "COURT_DECISION_CANCELLATION",
} as const;

export type EnforcementState =
    typeof ENFORCEMENT_STATES[keyof typeof ENFORCEMENT_STATES];


/**
 * Ожидаемые события для каждого состояния
 */
export const EXPECTED_EVENTS: Record<EnforcementState, string[]> = {

    [ENFORCEMENT_STATES.ENFORCEMENT_DOCUMENT_RECEIVED]: [
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.TYPO_CORRECTION_RECEIVED]: [
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED]: [
        ENFORCEMENT_STATES.TYPO_CORRECTION_LEFT_WITHOUT_ACTION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_RECEIVED,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
    ],

    [ENFORCEMENT_STATES.TYPO_CORRECTION_LEFT_WITHOUT_ACTION]: [
        ENFORCEMENT_STATES.TYPO_CORRECTION_RECEIVED,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
    ],

    [ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS]: [
        ENFORCEMENT_STATES.BANK_DOCUMENT_RECALL,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
    ],

    [ENFORCEMENT_STATES.BANK_WAITING_DOCUMENT]: [
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
        ENFORCEMENT_STATES.BANK_DOCUMENT_RETURNED,
    ],

    [ENFORCEMENT_STATES.PFR_WITHHOLDING]: [
        ENFORCEMENT_STATES.PFR_DOCUMENT_RECALL,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
    ],

    [ENFORCEMENT_STATES.PFR_WAITING_DOCUMENT]: [
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.PFR_DOCUMENT_RETURNED,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT]: [
        ENFORCEMENT_STATES.FSSP_STARTED,
        ENFORCEMENT_STATES.REFUSAL,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITHOUT_DOCUMENT,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITH_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
        ENFORCEMENT_STATES.FSSP_DOCUMENT_RECALL,
    ],

    [ENFORCEMENT_STATES.FSSP_STARTED]: [
        ENFORCEMENT_STATES.FSSP_STATUS_REQUEST,
        ENFORCEMENT_STATES.REFUSAL,
        ENFORCEMENT_STATES.FSSP_DOCUMENT_RECALL,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITHOUT_DOCUMENT,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITH_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.FSSP_STATUS_REQUEST]: [
        ENFORCEMENT_STATES.FSSP_DOCUMENT_RECALL,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITHOUT_DOCUMENT,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITH_DOCUMENT,
        ENFORCEMENT_STATES.FSSP_DOCUMENT_RETURNED,
        ENFORCEMENT_STATES.REFUSAL,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.FSSP_WAITING_DOCUMENT]: [
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.FSSP_DOCUMENT_RETURNED,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.BANK_DOCUMENT_RETURNED]: [
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.PFR_DOCUMENT_RETURNED]: [
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.FSSP_DOCUMENT_RETURNED]: [
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITHOUT_DOCUMENT]: [
        ENFORCEMENT_STATES.REFUSAL,
        ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITH_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.PROCEEDING_FINISHED_WITH_DOCUMENT]: [
        ENFORCEMENT_STATES.REFUSAL,
        ENFORCEMENT_STATES.SENDING_TO_PARTNERS,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
    ],

    [ENFORCEMENT_STATES.SENDING_TO_PARTNERS]: [
        ENFORCEMENT_STATES.FSSP_DOCUMENT_RETURNED,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
    ],

    [ENFORCEMENT_STATES.REFUSAL]: [
        ENFORCEMENT_STATES.BANK_BLOCK_ACCOUNTS,
        ENFORCEMENT_STATES.PFR_WITHHOLDING,
        ENFORCEMENT_STATES.FSSP_SENDING_DOCUMENT,
        ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION,
        ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.COURT_ORDER_CANCELLATION]: [
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    [ENFORCEMENT_STATES.COURT_DECISION_CANCELLATION]: [
        ENFORCEMENT_STATES.ENFORCEMENT_DOCUMENT_RECEIVED,
        ENFORCEMENT_STATES.TYPO_CORRECTION_REQUESTED,
    ],

    /**
     * Заглушки для состояний,
     * которые сами не запрашиваются отдельным API
     */
    [ENFORCEMENT_STATES.BANK_DOCUMENT_RECALL]: [],
    [ENFORCEMENT_STATES.PFR_DOCUMENT_RECALL]: [],
    [ENFORCEMENT_STATES.FSSP_DOCUMENT_RECALL]: [],
};